name: Regression tests
on:
  pull_request:
    branches: [ "main" ]
    types: [ opened, synchronize, labeled ]
jobs:
  examples_dry_run:
    name: Dry Run (${{ matrix.target }})
    if: ${{ github.event.label.name == 'needs-ci' ||
            github.event.pull_request.user.login == 'hanno-becker' ||
            github.event.pull_request.user.login == 'dop-amin' ||
            github.event.pull_request.user.login == 'mkannwischer'
            }}
    runs-on: ubuntu-latest
    strategy: 
      matrix:      
        target: [slothy.targets.arm_v7m.cortex_m7,slothy.targets.arm_v81m.cortex_m55r1, slothy.targets.arm_v81m.cortex_m85r1, slothy.targets.aarch64.cortex_a55, slothy.targets.aarch64.cortex_a72_frontend, slothy.targets.aarch64.apple_m1_firestorm_experimental, slothy.targets.aarch64.apple_m1_icestorm_experimental]
    steps:
    - uses: actions/checkout@v3
    - name: Install python dependencies
      run: |
        python3 -m venv venv
        ./venv/bin/python3 -m pip install -r requirements.txt
        echo BASH_ENV="./venv/bin/activate" >> $GITHUB_ENV
    - name: Run examples
      run: |
        python3 example.py --dry-run --only-target=${{ matrix.target }}
  tutorial:
    if: ${{ github.event.label.name == 'needs-ci' ||
            github.event.pull_request.user.login == 'hanno-becker' ||
            github.event.pull_request.user.login == 'dop-amin' ||
            github.event.pull_request.user.login == 'mkannwischer'
            }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install python dependencies
      run: |
        python3 -m venv venv
        ./venv/bin/python3 -m pip install -r requirements.txt
        echo BASH_ENV="./venv/bin/activate" >> $GITHUB_ENV
    - name: Run tutorial
      run: |
        (cd tutorial && ./tutorial_all.sh)
  examples_basic:
    if: ${{ github.event.label.name == 'needs-ci' ||
            github.event.pull_request.user.login == 'hanno-becker' ||
            github.event.pull_request.user.login == 'dop-amin' ||
            github.event.pull_request.user.login == 'mkannwischer'
            }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install python dependencies
      run: |
        python3 -m venv venv
        ./venv/bin/python3 -m pip install -r requirements.txt
        echo BASH_ENV="./venv/bin/activate" >> $GITHUB_ENV
    - name: Run examples
      run: |
        python3 example.py --examples simple0,simple1,simple0_loop,simple1_loop
  examples_ntt_kyber_dilithium_helium_core:
    if: ${{ github.event.label.name == 'needs-ci' ||
            github.event.pull_request.user.login == 'hanno-becker' ||
            github.event.pull_request.user.login == 'dop-amin' ||
            github.event.pull_request.user.login == 'mkannwischer'
            }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install python dependencies
      run: |
        python3 -m venv venv
        ./venv/bin/python3 -m pip install -r requirements.txt
        echo BASH_ENV="./venv/bin/activate" >> $GITHUB_ENV
    - name: Run examples
      run: |
        python3 example.py --examples ntt_kyber_1_23_45_67_m55,ntt_dilithium_12_34_56_78_m55 --timeout=300
  examples_ntt_kyber_dilithium_neon_core:
    if: ${{ github.event.label.name == 'needs-ci' ||
            github.event.pull_request.user.login == 'hanno-becker' ||
            github.event.pull_request.user.login == 'dop-amin' ||
            github.event.pull_request.user.login == 'mkannwischer'
            }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install python dependencies
      run: |
        python3 -m venv venv
        ./venv/bin/python3 -m pip install -r requirements.txt
        echo BASH_ENV="./venv/bin/activate" >> $GITHUB_ENV
    - name: Run examples
      run: |
        python3 example.py --examples ntt_kyber_123_4567_a55,ntt_dilithium_123_45678_a55 --timeout=300
  sqmag:
    if: ${{ github.event.label.name == 'needs-ci' ||
            github.event.pull_request.user.login == 'hanno-becker' ||
            github.event.pull_request.user.login == 'dop-amin' ||
            github.event.pull_request.user.login == 'mkannwischer'
            }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install python dependencies
      run: |
        python3 -m venv venv
        ./venv/bin/python3 -m pip install -r requirements.txt
        echo BASH_ENV="./venv/bin/activate" >> $GITHUB_ENV
    - name: Run examples
      run: |
        (cd paper/scripts && NO_LOG=Y ./slothy_sqmag.sh)
  fft:
    if: ${{ github.event.label.name == 'needs-ci' ||
            github.event.pull_request.user.login == 'hanno-becker' ||
            github.event.pull_request.user.login == 'dop-amin' ||
            github.event.pull_request.user.login == 'mkannwischer'
            }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install python dependencies
      run: |
        python3 -m venv venv
        ./venv/bin/python3 -m pip install -r requirements.txt
        echo BASH_ENV="./venv/bin/activate" >> $GITHUB_ENV
    - name: Run examples
      run: |
        (cd paper/scripts && NO_LOG=Y ./slothy_fft.sh)
